Album detail and Photo detail pages
haplo/clarita-frontend pull request #27
Opened 2023-04-10 21:49 UTC by natalieacevedo

Created photo detail and album detail pages.

Fixes #5 and #6.

2023-04-12 09:14 UTC, haplo commented on src/App.scss
> +  // .Main {
Avoid committing commented out code.

2023-04-12 09:14 UTC, haplo commented on src/App.scss
> +/////////////////por ahora
Always in English.

2023-04-12 09:15 UTC, haplo commented on src/App.scss
> +.routes-container {
Would be nice to have some sorting logic in the CSS files, e.g. alphabetical.

2023-04-12 09:18 UTC, haplo commented on src/assets/Rightarrow.tsx
File should be *RightArrow.tsx*.

2023-04-12 10:05 UTC, haplo requested changes

2023-04-12 10:05 UTC, haplo commented on src/assets/Rightarrow.tsx
> +function RigthArrow() {
Typo, `RightArrow`.

2023-04-12 10:05 UTC, haplo commented on src/assets/Rightarrow.tsx
File should be _RightArrow.tsx_, with a capital `A`.

2023-04-12 10:05 UTC, haplo commented on src/assets/x.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" str
Make it a component like the rest.

2023-04-12 10:05 UTC, haplo commented on src/assets/hamburguer.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-menu-2" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round
Make it a component like the rest.

2023-04-12 10:05 UTC, haplo commented on src/components/Drawer.tsx
> +        isOpen || windWidth > 900 ? "drawer-is-open-container" : ""
Avoid magic numbers, move `900` to a module-level constant, e.g. `DESKTOP_WIDTH_THRESHOLD`.

2023-04-12 10:05 UTC, haplo commented on src/components/Footer.tsx
> +  <div>
Are three nested divs necessary?

2023-04-12 10:05 UTC, haplo commented on src/components/Header.tsx
> +import logoAzul from "../assets/clogo.png"
English.

2023-04-12 10:05 UTC, haplo commented on src/components/Header.tsx
> +//import { Button, Container, Form, FormControl, Nav, Navbar } from "react-bootstrap";
Remove commented out code.

2023-04-12 10:05 UTC, haplo commented on src/components/NavigationDrawer.tsx
> +  console.log(photo.image_url)
Remove log.

2023-04-12 10:05 UTC, haplo commented on src/components/Photo.tsx
> +    const realPhotoLink = `${baseUrl}/api/v1/photo/${id}/file`
This should be moved to the _data_ module. There should be no API URLs in components or pages.

2023-04-12 10:05 UTC, haplo commented on src/components/PhotoList.tsx
> +import PhotoAlbum from "react-photo-album"
Keep third-party imports above app imports.

2023-04-12 10:05 UTC, haplo commented on src/components/PhotoThumb.tsx
> +interface NavigationDrawerParams {
Should be `PhotoThumbParams`.

2023-04-12 10:05 UTC, haplo commented on src/context/drawersContext.tsx
Let's call it _Drawer.tsx_, not necessary to have _Context_ in the name as it's already in the _contexts_ module.

BTW change _context_ to plural, _contexts_, to match the other modules _pages_ and _components_.

2023-04-12 10:05 UTC, haplo commented on src/context/drawersContext.tsx
> +//Drawer context
This comment doesn't help, either improve it to explain what the drawer is about or remove it.

2023-04-12 10:05 UTC, haplo commented on src/data/apiFoto.ts
Use always English, rename to `apiPhoto`.

2023-04-12 10:05 UTC, haplo commented on src/pages/PhotoInAlbumPage.tsx
>  import { useParams } from "react-router-dom"
Keep third-party imports at the top of the file, followed by app imports.

2023-04-12 10:05 UTC, haplo commented on src/pages/PhotoInAlbumPage.tsx
> +    console.warn("empty props in PhotoInAlbumPage")
Duplicated line due to mishandled merge conflict.

2023-04-12 10:05 UTC, haplo commented on src/pages/PhotoInAlbumPage.tsx
> +    return <h1>Info is loading</h1>
Duplicated line due to mishandled merge conflict.

2023-04-12 10:05 UTC, haplo commented on src/pages/PhotoPage.tsx
> +import { useEffect } from "react"
Keep third-party imports at the top of the file, followed by app imports.

2023-04-12 10:05 UTC, haplo commented on src/styles/arrowsStyles.scss
> +svg {
This is a global style, should probably go in main file.

2023-04-12 10:05 UTC, haplo commented on src/styles/arrowsStyles.scss
> +.up {
These class names are too generic, I suggest you make them `.svg-arrow .up`.

2023-04-12 10:05 UTC, haplo commented on src/styles/breadCrumbs.scss
> +.bread-crumb-link,
Use `breadcrumb` without the hyphen for consistency with other classes.

2023-04-12 10:05 UTC, haplo commented on src/styles/mixins.scss
> +//rgba(167, 210, 203, 0.6);
Remove commented out code.

2023-04-12 10:05 UTC, haplo commented on src/styles/mixins.scss
> +@import url("https://fonts.googleapis.com/css2?family=ABeeZee&family=Indie+Flower&family=Inter:wght@200;300&family=Libre+Franklin:wght@300&family=Lora:wght@600&family=Poppins:wght@200;300&family=Pres
Remove all references to external fonts.

2023-04-12 10:05 UTC, haplo commented on src/styles/photoDetail.scss
> +//rgba(167, 210, 203, 0.6);
Remove commented out code.

2023-04-12 10:05 UTC, haplo commented on src/styles/photoDetail.scss
> +  //enter code here
Remove comment.

2023-04-12 10:05 UTC, haplo commented on src/styles/photoDetail.scss
> +//   and (min-device-width: 1200px)
Comments don't match the media query below.

2023-04-12 10:05 UTC, haplo commented on src/styles/photoDetail.scss
> +        //  padding: 5rem; //esto mientrastanto
Remove commented out code.

2023-04-12 10:05 UTC, haplo commented on src/utils/photoUrl.ts
> +  // "/albums/:albumId/photos/:photoId"
Remove commented out code.

2023-04-13 10:57 UTC, natalieacevedo commented on src/assets/x.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" str
I deleted the file because I did not end up using it.

2023-04-13 11:00 UTC, natalieacevedo commented on src/assets/hamburguer.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-menu-2" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round
I deleted the file because I did not end up using it.

2023-04-13 11:06 UTC, natalieacevedo commented on src/components/Footer.tsx
> +  <div>
The three divs were result of a merge, I did not write them. I erased two and left the main footer div.

2023-04-13 11:28 UTC, natalieacevedo commented on src/components/Photo.tsx
> +    const realPhotoLink = `${baseUrl}/api/v1/photo/${id}/file`
As discussed, the image URL will be moved as an attribute of the API.

2023-04-13 11:53 UTC, natalieacevedo commented on src/styles/mixins.scss
> +//rgba(167, 210, 203, 0.6);
Also removed google fonts since they are not going to be utilized in the project.

2023-04-13 21:20 UTC, haplo approved these changes
Really nice work addressing all comments! :100: 

Ready to merge! :rocket:

2023-04-14 20:10 UTC, merged